### PR TITLE
moving to using gx for package management

### PR DESCRIPTION
**Pull request by whyrusleeping**
WIP.

Working on vendoring all of this with gx.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
alright, this looks about right.

I tried doing the global package paths, but that wont work right now because it breaks the 'canonical package names' stuff, `golang.org/x/crypto/sha3` expects to be imported by that exact path, unless its in a packages vendor directory then it doesnt matter (wat?).

**Comment by jbenet** [comment]
what do you mean by 
> `golang.org/x/crypto/sha3` expects to be imported by that exact path
?

**Comment by whyrusleeping** [comment]
this line: https://github.com/golang/crypto/blob/master/sha3/doc.go#L66

is the 'canonical import path' specifier, meaning that go programs must import it by that path and no other.
Godeps simply removes these lines, so i've followed suit in gx. 

We should now be able to do the global stuff, the only reason i havent done so yet is that having things vendored in repo makes CI easier for now.

**Comment by jbenet** [comment]
Go with modularity:

**Comment by jbenet** [comment]
(To clarify, I mean the "features" golang pushes for)

**Comment by cryptix** [comment]
It would be nice to not just remove this info but annotate it, like `gx: removed canoniocal import, was golang.org/x/....`. I fear the first bug where a blend of two different versions blows up an nobody knows whats going on.....

**Comment by whyrusleeping** [comment]
closed in favor of #13

**Pull request closed without merging**
